#!/bin/bash
sudo apt-get install pdfedit
sudo apt-get install dia
sudo apt-get install freemind
sudo apt-get install planner
sudo apt-get install fotowall
sudo apt-get install jkiwi
sudo apt-get install openoffice.org-base
sudo apt-get install scribus
sudo apt-get install xmind
sudo apt-get install gpaint
sudo apt-get install kolourpaint4
sudo apt-get install inkscape
sudo apt-get install gimp
sudo apt-get install digikam
sudo apt-get install gthumb
sudo apt-get install gwenview
sudo apt-get install cheese
sudo apt-get install ktoon
sudo apt-get install pencil
sudo apt-get install blender
sudo apt-get install sweethome3d
sudo apt-get install hugin
sudo apt-get install audacious
sudo apt-get install amarok
sudo apt-get install vlc
sudo apt-get install umplayer
sudo apt-get install smplayer
sudo apt-get install audacity
sudo apt-get install tuxguitar
sudo apt-get install rosegarden
sudo apt-get install musescore
sudo apt-get install hydrogen
sudo apt-get install qjackctl
sudo apt-get install ardour
sudo apt-get install xvidcap
sudo apt-get install guvcview
sudo apt-get install sound-juicer
sudo apt-get install acidrip
sudo apt-get install kino
sudo apt-get install kdenlive
sudo apt-get install openshot
sudo apt-get install imagination
sudo apt-get install dvdstyler
sudo apt-get install qdvdAuthor
sudo apt-get install winff
sudo apt-get install devede
sudo apt-get install oggconvert
sudo apt-get install k3b
sudo apt-get install dvdisaster
sudo apt-get install furiusisomount
sudo apt-get install pcmanx-mls-gtk2
sudo apt-get install kompozer
sudo apt-get install exe
sudo apt-get install pidgin
sudo apt-get install kopete
sudo apt-get install emesene
sudo apt-get install ekiga
sudo apt-get install gftp
sudo apt-get install filezilla
sudo apt-get install meiga
sudo apt-get install pppoeconf
sudo apt-get install miro
sudo apt-get install iptux
sudo apt-get install wireshark
sudo apt-get install scratch
sudo apt-get install kturtle
sudo apt-get install alice
sudo apt-get install fritzing
sudo apt-get install ktouch
sudo apt-get install ktuberling
sudo apt-get install gcompris
sudo apt-get install geogebra
sudo apt-get install drgeo
sudo apt-get install kig
sudo apt-get install kmplot
sudo apt-get install kbruch
sudo apt-get install kayali
sudo apt-get install kalgebra
sudo apt-get install geometria
sudo apt-get install wxmaxima
sudo apt-get install kalzium
sudo apt-get install ghemical
sudo apt-get install avogadro
sudo apt-get install gchempaint
sudo apt-get install bkchem
sudo apt-get install ballview
sudo apt-get install pymol
sudo apt-get install step
sudo apt-get install opticalraytracer
sudo apt-get install kstars
sudo apt-get install stellarium
sudo apt-get install celestia-gnome
sudo apt-get install kgeography
sudo apt-get install marble
sudo apt-get install google-earth-stable
sudo apt-get install klettres
sudo apt-get install kwordquiz
sudo apt-get install parley
sudo apt-get install anki
sudo apt-get install tuxmath
sudo apt-get install tuxtype
sudo apt-get install gnome-sudoku
sudo apt-get install gnotski
sudo apt-get install gnotravex
sudo apt-get install knetwalk
sudo apt-get install pinball
sudo apt-get install lbreakout2
sudo apt-get install frozen-bubble
sudo apt-get install kblocks
sudo apt-get install kolf
sudo apt-get install tuxpuck
sudo apt-get install supertux
sudo apt-get install pingus
sudo apt-get install supertuxkart
sudo apt-get install glchess
sudo apt-get install gnome-mahjongg
sudo apt-get install gnomine
sudo apt-get install aisleriot
sudo apt-get install shutter
sudo apt-get install whiteboard
sudo apt-get install wiican
sudo apt-get install ardesia
sudo apt-get install qjoypad
sudo apt-get install easystroke
sudo apt-get install curtain
sudo apt-get install spotlighter
sudo apt-get install convertall
sudo apt-get install posterazor
sudo apt-get install dolphin
sudo apt-get install workrave
sudo apt-get install tuxpaint
