#!/bin/bash
sudo apt-get install audacity
sudo apt-get install tuxguitar
sudo apt-get install rosegarden
sudo apt-get install musescore
sudo apt-get install hydrogen
sudo apt-get install ardour
sudo apt-get install xvidcap
sudo apt-get install guvcview
sudo apt-get install sound-juicer
sudo apt-get install acidrip
sudo apt-get install kino
sudo apt-get install kdenlive
sudo apt-get install openshot
sudo apt-get install imagination
sudo apt-get install dvdstyler
sudo apt-get install qdvdAuthor
sudo apt-get install winff
sudo apt-get install devede
sudo apt-get install oggconvert
sudo apt-get install k3b
sudo apt-get install dvdisaster
sudo apt-get install furiusisomount
